pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'OTP1', url: 'https://github.com/loharuu/school_stuff.git'
            }
        }
        stage('Build') {
            steps {
                dir("Docker") {
                    bat 'mvn clean install'
                }
                 // sh for linux and ios
            }
        }
        stage('Test') {
            steps {
            dir("Docker") {
                bat 'mvn test'}
            }
        }
        stage('Code Coverage') {
                steps {
                dir("Docker") {
                    bat 'mvn jacoco:report'}
                }
            }
        stage('Publish Test Results') {
            steps {
            dir("Docker") {
                junit '**/target/surefire-reports/*.xml'}
            }
        }
        stage('Publish Coverage Report') {
            steps {
            dir("Docker") {
                jacoco()}
            }
        }
    }
}
