pipeline {
    agent any

    environment {
        PATH = "C:\\Users\\olegd\\AppData\\Local\\Programs\\DockerDesktop\\resources\\bin\\docker"
        DOCKERHUB_CREDENTIALS_ID = 'docker'
        DOCKERHUB_REPO = 'oleruu/otp1'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'OTP1', url: 'https://github.com/loharuu/school_stuff.git'
            }
        }

        stage('Check Docker') {
            steps {
                bat '''
                    echo %PATH%
                    where docker
                    docker --version
                    docker info
                '''
            }
        }
        stage('Build') {
                    steps {
                        dir("Docker") {
                            bat 'mvn clean install'
                        }
                         // sh for linux and ios
                    }
                }
                stage('Test') {
                    steps {
                    dir("Docker") {
                        bat 'mvn test'}
                    }
                    }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry(
                        'https://index.docker.io/v1/',
                        DOCKERHUB_CREDENTIALS_ID
                    ) {
                        docker.image(
                            "${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}"
                        ).push()
                    }
                }
            }
        }
    }
}
